### ISSUE TITLE
SNI Support

### ISSUE THREAD

**Issue by adamcaudill** [arlimus/sslshake#2]
Given the large number of sites that require SNI (~30% of the Alexa top 1 million), ideally SNI support should be added to this.

I've not had time to write up a patch to add it; if I get a chance, I will, unless someone else gets to it first.

**Comment by supergicko** [comment]
@adamcaudill are you working on this currently?

**Comment by adamcaudill** [comment]
@supergicko It's on my todo list, but I've not started on it yet.

**Comment by adamcaudill** [comment]
I've submitted a PR that adds SNI - and ECC suites as well.

**Comment by supergicko** [comment]
@adamcaudill thank you so much
